= image:../../logo.svg[Boat Others] Boat Others -- Third Party Supporting and Extension Libs for link:../../README.md[Boat]
:toc:
:toclevels: 3
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com

== Introduction

Boat others provides third party supporting and extension for link:../../README.md[Boat].

== Supporting List

=== Protobuf: boat-protobuf

boat-protobuf provides `bean`, `convert` and `serialize` handlers and processors for protobuf type object:

* `ProtobufBeanResolveHandler`: Bean resolve handler supports protobuf types, extends from `BeanResolveHandler` (boat-core);
* `ProtobufBeanProvider`: `BeanConvertHandler.NewBeanProvider` (boat-core) supports protobuf types;
* `ProtobufBeans.PROTOBUF_BEAN_RESOLVER`: Bean resolve supports protobuf types, extends from `BeanResolver` (boat-core);
* ProtobufConverts.PROTOBUF_CONVERTER: Converter supports protobuf types, extends from `Converter` (boat-core);
* ProtobufJsons.PROTOBUF_OBJECT_MAPPER: ``Jackson``'s `ObjectMapper` (boat-serialize) supports protobuf types;
* ProtobufJsons.PROTOBUF_JSON_SERIALIZER: `JsonSerializer` (boat-serialize) supports protobuf types.

WARNING: `boat-protobuf` need `protoc` to compile protobuf files, some architectures don't support it (such as `ARM`).
Check whether your environment support: link:https://repo1.maven.org/maven2/com/google/protobuf/protoc/[]

.Java Examples
[source,java]
----
include::../boat-others-sample/src/test/java/sample/java/xyz/srclab/common/protobuf/ProtobufSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-others-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/protobuf/ProtobufSample.kt[]
----