= image:../../logo.svg[Boat Serialize] `boat-other`: Boat Others -- Third Party Supporting and Extension Libs for link:../../README.md[Boat]
:toc:
:toclevels: 3
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com

== Introduction

Boat others provides third party supporting and extension for link:../../README.md[Boat].

== Supporting List

=== Protobuf: boat-protobuf

boat-protobuf provides `bean`, `convert` and `serialize` handlers and processors for protobuf type object:

* `ProtobufBeanResolveHandler`: Bean resolve handler supporting protobuf type, extends from `BeanResolveHandler` (boat-core);
* `ProtobufBeans.PROTOBUF_BEAN_RESOLVER`: Bean resolve supporting protobuf type, extends from `BeanResolver` (boat-core);
* ProtobufConverts.PROTOBUF_CONVERTER: Converter supporting protobuf type, extends from `Converter` (boat-core);
* ProtobufJsons.PROTOBUF_OBJECT_MAPPER: ``Jackson``'s `ObjectMapper` (boat-serialize) supporting protobuf type;
* ProtobufJsons.PROTOBUF_JSON_SERIALIZER: `JsonSerializer` (boat-serialize) supporting protobuf type.

.Java Examples
[source,java]
----
include::../boat-others-sample/src/test/java/sample/java/xyz/srclab/common/protobuf/ProtobufSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-others-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/protobuf/ProtobufSample.kt[]
----