= image:../../logo.svg[Boat Core] `boat-core`: Boat Core -- link:../../README.md[Boat] 核心库
:toc:
:toclevels: 3
:toc-title: 目录
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com

== 简介

Boat core link:../../README.md[Boat] 的核心接口, 方法和工具, 包括:

* <<Lang>>: 基础包, 提供一系列核心接口和组件;
* <<Bean>>: Bean包, 支持快速便捷的`bean`操作;
* <<Convert>>: 类型转换包, 支持大量的类型间相互转换;
* <<Cache>>: 缓存包, 提供核心缓存接口和若干内置实现;
* <<Run>>: 关于运行线程的包, 提供 `Runner` 接口和实现;
* <<Bus>>: Bus包, 提供 `EventBus` 接口;
* <<Invoke>>: 提供 `Invoker` 接口和实现;
* <<Proxy>>: 提供 `ProxyClass` 来进行动态代理, 反射, `spring-core` 或 `cglib` 方式;
* <<State>>: 提供 `State` 接口来代表一个状态;
* <<Exception>>: 关于异常的包;
* <<Collect>>: 集合扩展包, 支持 `链式操作`, `多值Map`, 大量集合工具类等;
* <<Reflect>>: 反射扩展包, 提供许多便捷反射操作;
* <<IO>>: IO扩展包;
* <<Jvm>>: 提供JVM底层操作;
* <<Utils>>: 其他便捷工具包;
* <<Test>>: 提供用于测试的接口和工具;

== 用法

=== Lang

Lang包提供一系列核心接口和组件:

* 全局系统对象: `Current`, `Defaults`, `Environment`;
* 语法增强 (主要针对Java): `Let`, `Ref`, `Lazy`, `LazyString`;
* 字符串功能: `CharsFormat`, `CharsTemplate`, `NamingCase`;
* 特殊字符支持: `CtlChars`, `EscChars`, `CsiChars`, `SgrChars`;
* 访问接口: `SingleAccessor`, `MapAccessor`, `GenericSingleAccessor`, `GenericMapAccessor`;
* 辅助对象: SpecParser, CachingProductBuilder, Processing;
* 公共工具: Anys, Bools, Chars, Nums, Dates, Randoms, RandomSupplier, Compares, Checks, Requires, Enums, Loaders.

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/lang/LangSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/lang/LangSample.kt[]
----

=== Bean

Bean包, 支持快速便捷的`bean`操作:

* `Beans`: Bean操作的工具类;
* `BeanResolver`: 核心接口用来解析 `bean`, `Beans` 使用它的默认实现;
* `BeanResolveHandler`: `BeanResolver` 用来解析的处理器;
* `BeanMap`: 一种将 `bean` 和 `Map` 关联起来的 `Map`;
* `BeanType`: 用来描述 `bean` 结构的接口, 就像 `Class`;
* `PropertyType`: 用来描述 `bean` 属性的接口, 就像 `Field`;

TIP: `Beans` 在属性复制 (copyProperties) 上比 `Apache BeanUtils` 快20倍.

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/bean/BeanSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/bean/BeanSample.kt[]
----

=== Convert

Convert包提供大量的类型转换功能:

* `Converts`: 类型转换工具类;
* `Converter`: 类型转换的核心接口, `Converts` 使用它的默认实现;
* `ConvertHandler`: `Converter` 用来转换的处理器;
* `FastConverter`: 一种快速转换器;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/convert/ConvertSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/convert/ConvertSample.kt[]
----

=== Cache

Cache包提供缓存核心接口和内置实现:

* `Cache`: 核心缓存接口;
* `FastCache`: 使用 `WeakHashMap` 和 `ThreadLocal` 的实现;
* `CaffeineCache`: 使用 `Caffeine` 的实现;
* `GuavaCache`: 使用 `Guava` 的实现;
* `MapCache`: 使用 `Map` 的实现, 也就是让 `Map` 编程 `Cache`;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/cache/CacheSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/cache/CacheSample.kt[]
----

=== Run

Run包是关于运行线程的包, 提供 `Runner` 接口和实现:

* `Runner`: 用来运行线程的核心接口;
* `Running`: 代表一个运行中的实体;
* `Scheduler`: 用来执行调度的核心接口;
* `Scheduling`: 代表一个执行中的调度;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/run/RunSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/run/RunSample.kt[]
----

=== Bus

Bus包提供 `EventBus` 接口:

* `EventBus`: 事件总线接口的实现;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/bus/EventBusSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/bus/EventBusSample.kt[]
----

=== Invoke

Invoke包提供 `Invoker` 接口和实现:

* `Invoker`: 核心调用接口;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/invoke/InvokeSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/invoke/InvokeSample.kt[]
----

=== Proxy

Proxy包提供 `ProxyClass` 用带进行动态代理, 使用 `反射`, `spring-core` 或 `cglib` 方法:

* `ProxyClass`: 代理目标 `Class` 的核心接口;
* `ProxyMethod`: 代理的方法体;
* `ProxyClassFactory`: 创建 `ProxyClass` 的工厂, 内置 `Reflection`, `spring-core` 和 `cglib` 实现;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/proxy/ProxySample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/proxy/ProxySample.kt[]
----

=== State

State包提供 `State` 接口代表一个状态:

* `State`: 代表状态的核心接口;
* `StringState`: 字符串类型的 `State`;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/state/StateSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/state/StateSample.kt[]
----

=== Exception

Exception包提供关于 `Exception` 的实现和工具:

* `ExceptionStatus`: 继承 <<State>> 的状态, 用于 `Exception`;
* `StatusException`: 实现 `ExceptionStatus` 的异常;
* `ImpossibleException`: 代表一个不应该被抛出但确实被抛出的异常;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/exception/ExceptionSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/exception/ExceptionSample.kt[]
----

=== Collect

集合扩展包, 支持 `链式操作`, `多值Map`, 大量集合工具类等:

* `Collects`: 集合工具类;
* `Collecting`, `Mapping`: 提供链式操作的集合接口, 并且集成了常见集合的功能 (如 `Iterable`, `Collection`, `Set`, `List`);
* `IterableType`, `MapType`: 代表集合泛型类型;
* `MultiMaps`: `MultiMaps` 提供多值 `Map` 如 `SetMap`, `MutableSetMap`, `ListMap` 何 `MutableListMap`;
* `CopyOnWriteMap`: 实现copy-on-write操作的Map;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/collect/CollectSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/collect/CollectSample.kt[]
----

=== Reflect

反射扩展包, 提供许多便捷反射操作:

* `Reflects`: 反射工具类;
* `Types`: 用来构造泛型类型;
* `TypeRef`: 以直接代码的方式构造泛型类型;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/reflect/ReflectSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/reflect/ReflectSample.kt[]
----

=== IO

IO扩展包:

* `IOStreams`: 提供 `Input`/`Output`, `Reader`/`Writer` 操作的工具类;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/io/IOSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/io/IOSample.kt[]
----

=== Jvm

提供JVM底层操作:

* `Jvms`: 提供JVM底层操作;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/jvm/JvmSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/jvm/JvmSample.kt[]
----

=== Utils

其他便捷工具包:

* `Counter`: 简单的int/long计数器, 可以是原子的;
* `About`: 产品信息如 `About`, `Author`, `SemVer`;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/utils/UtilsSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/utils/UtilsSample.kt[]
----

=== Test

提供用于测试的接口和工具:

* `Tester`: 执行测试人物的核心接口;
* `TestTask`, `TestListener`: 测试任何和监听器的核心接口;
* `TestLogger`: 简单的测试日志工具;
* `Tests`: 测试工具类;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/core/test/TestSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/core/test/TestSample.kt[]
----