= Easy Starter: Base Integration Libraries for Java
Sun Qian <fredsuvn@163.com>
// v0.0.0, 2020-03-26
v1.0.0, 2020-04-12

Easy Starter is a base integration library for java, it consists of a set of core easy-components and selected third
base library with appropriate versions.

Core easy-components includes:

* easy-annotations: defines core annotations, some of them are optimized from jsr305;
* easy-common: base component for easy-starter. It encapsulates common operation for array, bean, builder, cache,
  collection, exception, lang, provider, reflect, shell, state, string, time, etc.;
* easy-bytecode: provides uniform bytecode interface and builtin implementations (cglib and spring-cglib);
* easy-common-proxy: provides proxy operation;
* easy-jni: provides jni operation;
* easy-test: provides assistant tools for testing.

There are also some selected third base library to use directly use:

* https://kotlinlang.org/[kotlin],
* https://commons.apache.org/proper/commons-lang/[commons-lang3],
* https://commons.apache.org/proper/commons-beanutils/[commons-beanutils],
* https://commons.apache.org/proper/commons-collections/[commons-collections],
* https://github.com/google/guava[Guava].

== Getting Started
Source code: https://github.com/srclab-projects/easy-common

From maven:

[source,xml,indent=0]
----
<dependency>
    <groupId>xyz.srclab.common</groupId>
    <artifactId>easy-common</artifactId>
    <version>${version}</version>
</dependency>
----

Other artifact in xyz.srclab.common:

[source,xml,indent=0]
----
<dependencies>
  <dependency>
      <groupId>xyz.srclab.common</groupId>
      <artifactId>easy-bom</artifactId>
      <version>${version}</version>
  </dependency>

  <dependency>
      <groupId>xyz.srclab.common</groupId>
      <artifactId>easy-test</artifactId>
      <version>${version}</version>
  </dependency>
</dependencies>
----

== Usage
Like its name, Easy for Common is very easy to use:

:sampledir: easy-sample/src/main/java/xyz/srclab/sample

=== Bean Operator
Bean operator is used for operating beans such as convert type, copy properties, populate properties and etc.:

[source,java]
----
include::{sampledir}/bean/BeanSample.java[]
----

=== Bytecode
Bytecode can dynamically create bean, proxy class. It use cglib or spring-cglib according to environment:

[source,java]
----
include::{sampledir}/bytecode/ByteCodeSample.java[]
----

=== Format
Format is used for formatting String, it support formatting as slf4j style, printf style and message style:

[source,java]
----
include::{sampledir}/format/FormatSample.java[]
----

=== Lang
Package lang provides some base but elegant type:

[source,java]
----
include::{sampledir}/lang/LangSample.java[]
----

=== Proxy
Proxy use bytecode to convenient proxy class:

[source,java]
----
include::{sampledir}/proxy/ProxySample.java[]
----

=== Reflect
Reflect Provides reflect methods without checked exception:

[source,java]
----
include::{sampledir}/reflect/ReflectSample.java[]
----


== License
Easy for Common is Open Source software released under the
https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].