package xyz.fslabo.common.reflect.proxy;

import xyz.fslabo.annotations.Nullable;

/**
 * Proxy class generated by {@link ProxyBuilder}.
 */
public interface ProxyClass {

    /**
     * Creates and returns a new proxy instance with empty constructor.
     *
     * @param <T> type of the instance
     * @return a new proxy instance
     * @throws ProxyException if any problem occurs
     */
    <T> T newInstance() throws ProxyException;

    /**
     * Returns actual generated proxy class.
     * <p>
     * This method may be return {@code null} if the generator of this proxy class is unsupported.
     *
     * @return actual generated proxy class
     */
    @Nullable
    Class<?> getProxyClass();
}
