= image:../../logo.svg[Fs Annotations] `fs-annotations`: Fs Annotations -- Annotations of link:../../README.md[Fs]
:toc:
:toclevels: 3
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com

Fs Annotations provides a set of annotations to help your codes stay tidy and clean:

* *DefaultNonNull*/*DefaultNullable*: It tells that all variables, fields, parameters, and other use of type are non-null/nullable by default in annotated scope, usually used in package-info.java;
* *NotNull*/*Nullable*: It tells that annotated variable, field, parameter, and other use of type is non-null/nullable;
* *JavaBean*: It tells that annotated type is a java-bean, which all properties are nullable by default;
* *Acceptable*/*Accepted*: It tells that annotated parameter only accepts specified types;
* *Rejectable*/*Rejected*: It tells that annotated parameter will reject specified types;
* *Written*: It tells that the parameter may be written;
* *Immutable*: It tells that annotated variable, field, parameter, and other use of type is immutable and thread-safe;
* *ThreadSafe*: It tells that annotated variable, field, parameter, and other use of type is thread-safe;
* *ThreadSafeIf*: It tells that annotated variable, field, parameter, and other use of type is thread-safe if specified conditions were met;

.Java Examples
[source,java]
----
include::../../boat-sample/src/test/java/sample/java/xyz/srclab/annotations/AnnotationSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/annotations/AnnotationSample.kt[]
----