= _fs_: Core Libraries of link:{srclab-url}[SrcLab] and link:{me-url}[Me] for JVM
:toc:
:toclevels: 3
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com
:url: https://github.com/fredsuvn/fs
:srclab-url: https://github.com/srclab-projects
:me-url: https://github.com/fredsuvn
:fs-version: 0.0.0

== Introduction

_fs_ is a set of Java/Kotlin libraries (JDK 1.8+), mostly written by java,
widely used in projects of link:{srclab-url}[SrcLab] and link:{me-url}[me].
It provides many fast and convenient interfaces, functions and utilities.

_fs_ includes:

* link:../gek-annotations/[fs-annotation]: Annotations; link:../gek-annotations/docs/DOCUMENTATION_en.adoc[javadoc];
* link:../gek-core/[fs-core]: Core lib; link:../gek-core/docs/DOCUMENTATION_en.adoc[javadoc];
* link:../gek-kotlin/[fs-kotlin]: Kotlin support; link:../gek-kotlin/docs/DOCUMENTATION_en.adoc[javadoc];
* link:../gek-test/[fs-test]: Testing support;
* link:../gek-bom/[fs-bom]: BOM;

Generally just import:

* link:../gek-core/[fs-core].

== Getting

=== Get _fs_

.Gradle
[source,groovy,subs="attributes+"]
----
implementation "xyz.fsgek:fs-core:{fs-version}"
----

.Maven
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>xyz.fsgek</groupId>
  <artifactId>fs-core</artifactId>
  <version>{fs-version}</version>
</dependency>
----

=== With BOM

.Gradle
[source,groovy,subs="attributes+"]
----
api platform("xyz.fsgek:boat-bom:{fs-version}")
----

.Maven
[source,xml,subs="attributes+"]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>xyz.fsgek</groupId>
      <artifactId>fs-bom</artifactId>
      <version>{fs-version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
----