= image:../logo.svg[Boat] Boat: SrcLab Core Libraries for Java/kotlin
:toc:
:toclevels: 3
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/boat
:srclab-url: https://github.com/srclab-projects
:boat-version: 0.0.1

== Introduction

Boat is a set of core Java/Kotlin libraries (JDK 1.8+), mostly written by kotlin, widely used on JVM projects within link:{srclab-url}[SrcLab].
It provides many fast and convenient interfaces, functions and utilities.

[[boat-include]]
Boat includes:

* link:../boat-annotations/README.md[boat-annotations]: Core annotations;
* link:../boat-core/README.md[boat-core]: Core lib;
* link:../boat-serialize/README.md[boat-serialize]: Serialization and deserialization lib (supports `JSON`);
* link:../boat-codec/README.md[boat-codec]: Codec lib (supports `HEX`, `BASE64`, `SHA`, `MD`, `HMAC`, `AES`, `RSA`, `SM2`, etc.);
* link:../boat-id/README.md[boat-id]: Fast ID generation lib;
* link:../boat-others/README.md[boat-others]: Third party supporting and extension lib (such as `protobuf`);

* link:../boat-test/[boat-test]: Testing libs dependencies management project;
* link:../boat-bom/[boat-bom]: BOM (gradle platform) project;

If you want to import common jars at once (`annotations`, `core`, `codec`, `serialize` and `id`), just import:

* link:../boat/[boat].

== Getting

=== Get Boat

.Gradle
[source,groovy,subs="attributes+"]
----
implementation "xyz.srclab.common:boat:{boat-version}"
----

.Maven
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>xyz.srclab.common</groupId>
  <artifactId>boat</artifactId>
  <version>{boat-version}</version>
</dependency>
----

=== With BOM

.Gradle
[source,groovy,subs="attributes+"]
----
api implementation("xyz.srclab.common:boat-bom:{boat-version}")
----

.Maven
[source,xml,subs="attributes+"]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>xyz.srclab.common</groupId>
      <artifactId>boat</artifactId>
      <version>{boat-version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
----

.Source Code
{url}

== Usages

Click their <<boat-include, links>>.