= image:../logo.svg[Boat] Boat: SrcLab的Java/kotlin核心基础库
:toc:
:toclevels: 3
:toc-title: 目录
:last-update-label!:
孙谦 <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/boat
:srclab-url: https://github.com/srclab-projects
:boat-version: 0.0.1

== 简介

Boat是一组Java/Kotlin核心库集合（JDK 1.8+）, 主要由Kotlin编写, 广泛应用于 link:{srclab-url}[SrcLab] 里的项目.
它提供了许多方便快捷的接口, 函数和工具.

[[boat-include]]
Boat 包括:

* link:../boat-annotations/README.md[boat-annotations]: 核心注解;
* link:../boat-core/README.md[boat-core]: 核心库;
* link:../boat-serialize/README.md[boat-serialize]: 序列化和反序列化核心库 (支持 `JSON`);
* link:../boat-codec/README.md[boat-codec]: 编码核心库 (支持 `HEX`, `BASE64`, `SHA`, `MD`, `HMAC`, `AES`, `RSA`, `SM2` 等);
* link:../boat-id/README.md[boat-id]: 快速ID生成框架;
* link:../boat-others/README.md[boat-others]: 第三方支持和扩展库 (如 `protobuf`);

* link:../boat-test/[boat-test]: 测试库的依赖管理工程;
* link:../boat-bom/[boat-bom]: BOM (gradle platform) project;

如果你需要一次性导入常用库 (`annotations`, `core`, `codec`, `serialize` and `id`), 只需要导入:

* link:../boat/[boat].

== 获取

=== 获取 Boat

.Gradle
[source,groovy,subs="attributes+"]
----
implementation "xyz.srclab.common:boat:{boat-version}"
----

.Maven
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>xyz.srclab.common</groupId>
  <artifactId>boat</artifactId>
  <version>{boat-version}</version>
</dependency>
----

=== 使用 BOM

.Gradle
[source,groovy,subs="attributes+"]
----
api implementation("xyz.srclab.common:boat-bom:{boat-version}")
----

.Maven
[source,xml,subs="attributes+"]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>xyz.srclab.common</groupId>
      <artifactId>boat</artifactId>
      <version>{boat-version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
----

.Source Code
{url}

== 用法

直接点击他们的 <<boat-include, 链接>>.