= image:../logo.svg[Boat] Boat: SrcLab Core Libraries for Java/kotlin
:toc:
:toclevels: 3
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/boat
:license: https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license]

:qq-group: QQ group: 1037555759
:boat-version: 0.0.1

== Introduction

Boat is a set of core Java/Kotlin libraries (JDK 1.8+), mostly written by kotlin, widely used on JVM projects within SrcLab.
It provides many fast and convenient interfaces, functions and utilities.

.Boat includes:
* *boat-annotations*: Core annotations, such as @Nullable, @NotNull, @DefaultNullable, @DefaultNotNull;
* *boat-core*: Core and basic interfaces, functions and utilities;
* *boat-serialize*: Serialization and deserialization interfaces and utilities (for json and more);
* *boat-codec*: Codec interfaces and utilities (supports hex, base64, SHA, MD, HMAC, AES, RSA, SM2, etc.);
* *boat-id*: A lightweight ID generation framework;
* *boat-test*: Test dependencies management, to import common test libraries in test scope;
* *boat-bom*: Boat Bom.

* *boat-others*: Boat also contains libraries for supporting special or third parties, see link:../boat-others/README.md[boat-others].

If you want to import common above modules at once (core, codec, serialize and id), just import:

* *boat*: To import common Boat modules including core, codec, serialize and id.

== Getting

.Gradle
[source,groovy,subs="attributes+"]
----
implementation("xyz.srclab.common:boat:{boat-version}")
----

.Maven
[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>xyz.srclab.common</groupId>
    <artifactId>boat</artifactId>
    <version>{boat-version}</version>
</dependency>
----

.Source Code
{url}

== Usage

=== Boat Annotations (boat-annotations)

Boat Annotations provides a set of annotations to make codes clear and clean:

* *DefaultNonNull*/*DefaultNullable*: It tells that all variables, fields, parameters, and other use of type are non-null/nullable by default in annotated scope, usually used in package-info.java;
* *NotNull*/*Nullable*: It tells that annotated variable, field, parameter, and other use of type is non-null/nullable;
* *JavaBean*: It tells that annotated type is a java-bean, which all properties are nullable by default;
* *Acceptable*/*Accepted*: It tells that annotated parameter only accepts specified types.
* *Rejectable*/*Rejected*: It tells that annotated parameter will reject specified types.
* *Written*: It tells that the parameter may be written;
* *Immutable*: It tells that annotated variable, field, parameter, and other use of type is immutable and thread-safe;
* *ThreadSafe*: It tells that annotated variable, field, parameter, and other use of type is thread-safe;
* *ThreadSafeIf*: It tells that annotated variable, field, parameter, and other use of type is thread-safe if specified conditions were met;

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/annotations/AnnotationSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/annotations/AnnotationSample.kt[]
----

=== Boat Core (boat-core)

==== Lang

Lang package provides base and enhancement interfaces, functions and utilities for Java/Kotlin:

* Global runtime, context, default and environment objects: Current, Defaults, Environment;
* Syntax enhancement (mainly for Java): Let, Ref, Lazy, LazyString;
* String/CharSequence functions: CharsFormat, CharsTemplate, NamingCase;
* Special character support: CtlChars, EscChars, CsiChars, SgrChars;
* Core and helper interfaces: Accessor (and GenericAccessor), Serial, SpecParser, CachingProductBuilder, Processing;
* Common utilities: Anys, Bools, Chars, Nums, Dates, Randoms, Compares, Checks, Requires, Enums, Loaders.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/lang/LangSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/lang/LangSample.kt[]
----

==== Bean

Bean package provides powerful bean operation ability:

* Beans: Default utilities for bean operation;
* BeanResolver: Core Interface to resolver bean, Beans use its default implementation;

TIP: In copy-properties function, It is more than 20 times faster than Apache BeanUtils.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/bean/BeanSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/bean/BeanSample.kt[]
----

==== Bus

Bus package provide EventBus.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/bus/EventBusSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/bus/EventBusSample.kt[]
----

==== Cache

Boat provides a Cache interface and several implementations:

* Cache: Cache core interface;
* FastCache: Implemented by WeakHashMap and ThreadLocal;
* CaffeineCache: Implemented by Caffeine;
* GuavaCache: Implemented by Guava;
* MapCache: Map as Cache;
* ThreadLocalCache: ThreadLocalMap as Cache.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/cache/CacheSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/cache/CacheSample.kt[]
----

==== Collect

Collect package provides interfaces, utilities and Ops operation for collection and array:

* Collects: Utilities for Collection;
* ArrayCollects: Utilities for Array;
* IterableOps, ListOps, SetOps, MapOps: Ops interfaces, provide chain operation, mainly for Java;
* SequenceOps: Ops for Sequence;
* IterableType, MapType: Meta type interfaces for generic Collection types;
* MultiMaps: MultiMaps provides multi-values Map such as SetMap, MutableSetMap, ListMap and MutableListMap.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/collect/CollectSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/collect/CollectSample.kt[]
----

==== Convert

Convert package provides type-conversion function：

* Converts: Utilities for conversion;
* Converter: Core interfaces for type-conversion, Converts use its default implementation;
* FastConverter: Fast and narrowing version of Converter.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/convert/ConvertSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/convert/ConvertSample.kt[]
----

==== Exception

Exception package provides StatusException and ExceptionStatus extended from State (see <<State>>), and a ShouldNotException.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/exception/ExceptionSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/exception/ExceptionSample.kt[]
----

==== Invoke

Invoke package provides Invoker interface to call methods (for Java) and functions (for Kotlin).

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/invoke/InvokeSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/invoke/InvokeSample.kt[]
----

==== Jvm

Jvm package provides Jvms utilities classes to get JVM infos.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/jvm/JvmSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/jvm/JvmSample.kt[]
----

==== Proxy

Proxy package provides Class proxy function with spring-cglib, cglib or JDK proxy.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/proxy/ProxySample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/proxy/ProxySample.kt[]
----

==== Reflect

Reflect package provides utilities classes:

* Reflects: Provides reflect operations;
* Types: To build generic types;
* TypeRef: To build a type reference.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/reflect/ReflectSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/reflect/ReflectSample.kt[]
----

==== Run

Run package provides Runner and Scheduler interfaces to run codes in threads or coroutines.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/run/RunSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/run/RunSample.kt[]
----

==== State

State package provides State interface to help build custom state or status type.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/state/StateSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/state/StateSample.kt[]
----

==== Utils

Other helpful utilities:

* Counter: Simple counter for int/long, amy atomic;
* About: Product info such as About, Author, SemVer.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/utils/UtilsSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/utils/UtilsSample.kt[]
----

==== Test

Test package provides simple test tools:

* Tester: interface to start test tasks;
* TestLogger: simple logger for testing;
* TestTask and TestListener: test task and listener;
* Tests: common utilities class for test.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/test/TestSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/test/TestSample.kt[]
----

=== Boat Serialize (boat-serialize)

Boat Serialize (should import boat-serialize) provides core Serializer interface for serialization:

* Serializer: Core interface for serialization;
* JsonSerials: JSON serialization utilities;
* JsonSerial: Core interface for JSON serialization, JsonSerials use its default implementation (Jackson);
* Json: Core interface denote a JSON object.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/serialize/SerializeSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/serialize/SerializeSample.kt[]
----

=== Boat Codec (boat-codec)

Boat Codec (should import boat-codec) provides Codec, CodecKeys, AesKeys and other interfaces to do with codec functions, supports hex, base64, AES, RSA, SM2 and more algorithms:

* Codec: Core interface and utilities for codec function;
* CodecKeys: Utilities for codec keys;
* AesKeys: Utilities for AES keys.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/codec/CodecSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/codec/CodecSample.kt[]
----

=== Boat Id (boat-id)

Boat ID (should import boat-id) is a lightweight and fast id generation framework.
It provides IdFactory and a set of interface to generate id:

* IdFactory: Core interface to generate new id;
* IdComponentFactory: Core interface to generator component of an id;
* AbstractIdFactory: Skeletal IdFactory to help implement full IdFactory;
* StringIdFactory: Skeletal IdFactory to help implement String-id-type IdFactory;

Boat ID also provides StringIdSpec, a String-type IdFactory, can build new id from a specification string, see its javadoc.

.Java Examples
[source,java]
----
include::../boat-sample/src/test/java/sample/java/xyz/srclab/common/id/IdSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-sample/src/test/kotlin/sample/kotlin/xyz/srclab/common/id/IdSample.kt[]
----

== Contribution and Contact

* {emaill}
* {url}
* {qq-group}

== License

{license}