// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package test.protobuf;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Enum em = 1;</code>
   * @return The enum numeric value on the wire for em.
   */
  int getEmValue();
  /**
   * <code>.Enum em = 1;</code>
   * @return The em.
   */
  test.protobuf.Enum getEm();

  /**
   * <code>string str = 2;</code>
   * @return The str.
   */
  java.lang.String getStr();
  /**
   * <code>string str = 2;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();

  /**
   * <code>int64 num = 3;</code>
   * @return The num.
   */
  long getNum();

  /**
   * <code>repeated string text = 4;</code>
   * @return A list containing the text.
   */
  java.util.List<java.lang.String>
      getTextList();
  /**
   * <code>repeated string text = 4;</code>
   * @return The count of text.
   */
  int getTextCount();
  /**
   * <code>repeated string text = 4;</code>
   * @param index The index of the element to return.
   * @return The text at the given index.
   */
  java.lang.String getText(int index);
  /**
   * <code>repeated string text = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the text at the given index.
   */
  com.google.protobuf.ByteString
      getTextBytes(int index);

  /**
   * <code>map&lt;string, string&gt; entry = 5;</code>
   */
  int getEntryCount();
  /**
   * <code>map&lt;string, string&gt; entry = 5;</code>
   */
  boolean containsEntry(
      java.lang.String key);
  /**
   * Use {@link #getEntryMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getEntry();
  /**
   * <code>map&lt;string, string&gt; entry = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getEntryMap();
  /**
   * <code>map&lt;string, string&gt; entry = 5;</code>
   */

  java.lang.String getEntryOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; entry = 5;</code>
   */

  java.lang.String getEntryOrThrow(
      java.lang.String key);
}
