// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package test.protobuf;

/**
 * Protobuf type {@code Data}
 */
public final class Data extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Data)
    DataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Data.newBuilder() to construct.
  private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Data() {
    em_ = 0;
    str_ = "";
    text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    bytes_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Data();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Data(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            em_ = rawValue;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            str_ = s;
            break;
          }
          case 24: {

            num_ = input.readInt64();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              text_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            text_.add(s);
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              entry_ = com.google.protobuf.MapField.newMapField(
                  EntryDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<String, String>
            entry__ = input.readMessage(
                EntryDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            entry_.getMutableMap().put(
                entry__.getKey(), entry__.getValue());
            break;
          }
          case 48: {

            uint32_ = input.readUInt32();
            break;
          }
          case 56: {

            uint64_ = input.readUInt64();
            break;
          }
          case 69: {

            fixed32_ = input.readFixed32();
            break;
          }
          case 73: {

            fixed64_ = input.readFixed64();
            break;
          }
          case 85: {

            sfixed32_ = input.readSFixed32();
            break;
          }
          case 89: {

            sfixed64_ = input.readSFixed64();
            break;
          }
          case 96: {

            sint32_ = input.readSInt32();
            break;
          }
          case 104: {

            sint64_ = input.readSInt64();
            break;
          }
          case 114: {

            bytes_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        text_ = text_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Message.internal_static_Data_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetEntry();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Message.internal_static_Data_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Data.class, Builder.class);
  }

  public static final int EM_FIELD_NUMBER = 1;
  private int em_;
  /**
   * <code>.Enum em = 1;</code>
   * @return The enum numeric value on the wire for em.
   */
  @Override public int getEmValue() {
    return em_;
  }
  /**
   * <code>.Enum em = 1;</code>
   * @return The em.
   */
  @Override public Enum getEm() {
    @SuppressWarnings("deprecation")
    Enum result = Enum.valueOf(em_);
    return result == null ? Enum.UNRECOGNIZED : result;
  }

  public static final int STR_FIELD_NUMBER = 2;
  private volatile Object str_;
  /**
   * <code>string str = 2;</code>
   * @return The str.
   */
  @Override
  public String getStr() {
    Object ref = str_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      str_ = s;
      return s;
    }
  }
  /**
   * <code>string str = 2;</code>
   * @return The bytes for str.
   */
  @Override
  public com.google.protobuf.ByteString
      getStrBytes() {
    Object ref = str_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      str_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUM_FIELD_NUMBER = 3;
  private long num_;
  /**
   * <code>int64 num = 3;</code>
   * @return The num.
   */
  @Override
  public long getNum() {
    return num_;
  }

  public static final int TEXT_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList text_;
  /**
   * <code>repeated string text = 4;</code>
   * @return A list containing the text.
   */
  public com.google.protobuf.ProtocolStringList
      getTextList() {
    return text_;
  }
  /**
   * <code>repeated string text = 4;</code>
   * @return The count of text.
   */
  public int getTextCount() {
    return text_.size();
  }
  /**
   * <code>repeated string text = 4;</code>
   * @param index The index of the element to return.
   * @return The text at the given index.
   */
  public String getText(int index) {
    return text_.get(index);
  }
  /**
   * <code>repeated string text = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the text at the given index.
   */
  public com.google.protobuf.ByteString
      getTextBytes(int index) {
    return text_.getByteString(index);
  }

  public static final int ENTRY_FIELD_NUMBER = 5;
  private static final class EntryDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                Message.internal_static_Data_EntryEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> entry_;
  private com.google.protobuf.MapField<String, String>
  internalGetEntry() {
    if (entry_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EntryDefaultEntryHolder.defaultEntry);
    }
    return entry_;
  }

  public int getEntryCount() {
    return internalGetEntry().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; entry = 5;</code>
   */

  @Override
  public boolean containsEntry(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetEntry().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEntryMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getEntry() {
    return getEntryMap();
  }
  /**
   * <code>map&lt;string, string&gt; entry = 5;</code>
   */
  @Override

  public java.util.Map<String, String> getEntryMap() {
    return internalGetEntry().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; entry = 5;</code>
   */
  @Override

  public String getEntryOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetEntry().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; entry = 5;</code>
   */
  @Override

  public String getEntryOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetEntry().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int UINT32_FIELD_NUMBER = 6;
  private int uint32_;
  /**
   * <code>uint32 uint32 = 6;</code>
   * @return The uint32.
   */
  @Override
  public int getUint32() {
    return uint32_;
  }

  public static final int UINT64_FIELD_NUMBER = 7;
  private long uint64_;
  /**
   * <code>uint64 uint64 = 7;</code>
   * @return The uint64.
   */
  @Override
  public long getUint64() {
    return uint64_;
  }

  public static final int FIXED32_FIELD_NUMBER = 8;
  private int fixed32_;
  /**
   * <code>fixed32 fixed32 = 8;</code>
   * @return The fixed32.
   */
  @Override
  public int getFixed32() {
    return fixed32_;
  }

  public static final int FIXED64_FIELD_NUMBER = 9;
  private long fixed64_;
  /**
   * <code>fixed64 fixed64 = 9;</code>
   * @return The fixed64.
   */
  @Override
  public long getFixed64() {
    return fixed64_;
  }

  public static final int SFIXED32_FIELD_NUMBER = 10;
  private int sfixed32_;
  /**
   * <code>sfixed32 sfixed32 = 10;</code>
   * @return The sfixed32.
   */
  @Override
  public int getSfixed32() {
    return sfixed32_;
  }

  public static final int SFIXED64_FIELD_NUMBER = 11;
  private long sfixed64_;
  /**
   * <code>sfixed64 sfixed64 = 11;</code>
   * @return The sfixed64.
   */
  @Override
  public long getSfixed64() {
    return sfixed64_;
  }

  public static final int SINT32_FIELD_NUMBER = 12;
  private int sint32_;
  /**
   * <code>sint32 sint32 = 12;</code>
   * @return The sint32.
   */
  @Override
  public int getSint32() {
    return sint32_;
  }

  public static final int SINT64_FIELD_NUMBER = 13;
  private long sint64_;
  /**
   * <code>sint64 sint64 = 13;</code>
   * @return The sint64.
   */
  @Override
  public long getSint64() {
    return sint64_;
  }

  public static final int BYTES_FIELD_NUMBER = 14;
  private com.google.protobuf.ByteString bytes_;
  /**
   * <code>bytes bytes = 14;</code>
   * @return The bytes.
   */
  @Override
  public com.google.protobuf.ByteString getBytes() {
    return bytes_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (em_ != Enum.E1.getNumber()) {
      output.writeEnum(1, em_);
    }
    if (!getStrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, str_);
    }
    if (num_ != 0L) {
      output.writeInt64(3, num_);
    }
    for (int i = 0; i < text_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, text_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetEntry(),
        EntryDefaultEntryHolder.defaultEntry,
        5);
    if (uint32_ != 0) {
      output.writeUInt32(6, uint32_);
    }
    if (uint64_ != 0L) {
      output.writeUInt64(7, uint64_);
    }
    if (fixed32_ != 0) {
      output.writeFixed32(8, fixed32_);
    }
    if (fixed64_ != 0L) {
      output.writeFixed64(9, fixed64_);
    }
    if (sfixed32_ != 0) {
      output.writeSFixed32(10, sfixed32_);
    }
    if (sfixed64_ != 0L) {
      output.writeSFixed64(11, sfixed64_);
    }
    if (sint32_ != 0) {
      output.writeSInt32(12, sint32_);
    }
    if (sint64_ != 0L) {
      output.writeSInt64(13, sint64_);
    }
    if (!bytes_.isEmpty()) {
      output.writeBytes(14, bytes_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (em_ != Enum.E1.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, em_);
    }
    if (!getStrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, str_);
    }
    if (num_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, num_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < text_.size(); i++) {
        dataSize += computeStringSizeNoTag(text_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTextList().size();
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetEntry().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      entry__ = EntryDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, entry__);
    }
    if (uint32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, uint32_);
    }
    if (uint64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, uint64_);
    }
    if (fixed32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(8, fixed32_);
    }
    if (fixed64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(9, fixed64_);
    }
    if (sfixed32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed32Size(10, sfixed32_);
    }
    if (sfixed64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed64Size(11, sfixed64_);
    }
    if (sint32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(12, sint32_);
    }
    if (sint64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt64Size(13, sint64_);
    }
    if (!bytes_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(14, bytes_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Data)) {
      return super.equals(obj);
    }
    Data other = (Data) obj;

    if (em_ != other.em_) return false;
    if (!getStr()
        .equals(other.getStr())) return false;
    if (getNum()
        != other.getNum()) return false;
    if (!getTextList()
        .equals(other.getTextList())) return false;
    if (!internalGetEntry().equals(
        other.internalGetEntry())) return false;
    if (getUint32()
        != other.getUint32()) return false;
    if (getUint64()
        != other.getUint64()) return false;
    if (getFixed32()
        != other.getFixed32()) return false;
    if (getFixed64()
        != other.getFixed64()) return false;
    if (getSfixed32()
        != other.getSfixed32()) return false;
    if (getSfixed64()
        != other.getSfixed64()) return false;
    if (getSint32()
        != other.getSint32()) return false;
    if (getSint64()
        != other.getSint64()) return false;
    if (!getBytes()
        .equals(other.getBytes())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EM_FIELD_NUMBER;
    hash = (53 * hash) + em_;
    hash = (37 * hash) + STR_FIELD_NUMBER;
    hash = (53 * hash) + getStr().hashCode();
    hash = (37 * hash) + NUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNum());
    if (getTextCount() > 0) {
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getTextList().hashCode();
    }
    if (!internalGetEntry().getMap().isEmpty()) {
      hash = (37 * hash) + ENTRY_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEntry().hashCode();
    }
    hash = (37 * hash) + UINT32_FIELD_NUMBER;
    hash = (53 * hash) + getUint32();
    hash = (37 * hash) + UINT64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUint64());
    hash = (37 * hash) + FIXED32_FIELD_NUMBER;
    hash = (53 * hash) + getFixed32();
    hash = (37 * hash) + FIXED64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFixed64());
    hash = (37 * hash) + SFIXED32_FIELD_NUMBER;
    hash = (53 * hash) + getSfixed32();
    hash = (37 * hash) + SFIXED64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSfixed64());
    hash = (37 * hash) + SINT32_FIELD_NUMBER;
    hash = (53 * hash) + getSint32();
    hash = (37 * hash) + SINT64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSint64());
    hash = (37 * hash) + BYTES_FIELD_NUMBER;
    hash = (53 * hash) + getBytes().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Data parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Data parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Data parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Data parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Data parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Data parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Data parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Data parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Data parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Data parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Data parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Data parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Data prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Data}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Data)
      DataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_Data_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetEntry();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableEntry();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Data.class, Builder.class);
    }

    // Construct using test.protobuf.Data.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      em_ = 0;

      str_ = "";

      num_ = 0L;

      text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableEntry().clear();
      uint32_ = 0;

      uint64_ = 0L;

      fixed32_ = 0;

      fixed64_ = 0L;

      sfixed32_ = 0;

      sfixed64_ = 0L;

      sint32_ = 0;

      sint64_ = 0L;

      bytes_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Message.internal_static_Data_descriptor;
    }

    @Override
    public Data getDefaultInstanceForType() {
      return Data.getDefaultInstance();
    }

    @Override
    public Data build() {
      Data result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Data buildPartial() {
      Data result = new Data(this);
      int from_bitField0_ = bitField0_;
      result.em_ = em_;
      result.str_ = str_;
      result.num_ = num_;
      if (((bitField0_ & 0x00000001) != 0)) {
        text_ = text_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.text_ = text_;
      result.entry_ = internalGetEntry();
      result.entry_.makeImmutable();
      result.uint32_ = uint32_;
      result.uint64_ = uint64_;
      result.fixed32_ = fixed32_;
      result.fixed64_ = fixed64_;
      result.sfixed32_ = sfixed32_;
      result.sfixed64_ = sfixed64_;
      result.sint32_ = sint32_;
      result.sint64_ = sint64_;
      result.bytes_ = bytes_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Data) {
        return mergeFrom((Data)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Data other) {
      if (other == Data.getDefaultInstance()) return this;
      if (other.em_ != 0) {
        setEmValue(other.getEmValue());
      }
      if (!other.getStr().isEmpty()) {
        str_ = other.str_;
        onChanged();
      }
      if (other.getNum() != 0L) {
        setNum(other.getNum());
      }
      if (!other.text_.isEmpty()) {
        if (text_.isEmpty()) {
          text_ = other.text_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTextIsMutable();
          text_.addAll(other.text_);
        }
        onChanged();
      }
      internalGetMutableEntry().mergeFrom(
          other.internalGetEntry());
      if (other.getUint32() != 0) {
        setUint32(other.getUint32());
      }
      if (other.getUint64() != 0L) {
        setUint64(other.getUint64());
      }
      if (other.getFixed32() != 0) {
        setFixed32(other.getFixed32());
      }
      if (other.getFixed64() != 0L) {
        setFixed64(other.getFixed64());
      }
      if (other.getSfixed32() != 0) {
        setSfixed32(other.getSfixed32());
      }
      if (other.getSfixed64() != 0L) {
        setSfixed64(other.getSfixed64());
      }
      if (other.getSint32() != 0) {
        setSint32(other.getSint32());
      }
      if (other.getSint64() != 0L) {
        setSint64(other.getSint64());
      }
      if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
        setBytes(other.getBytes());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Data parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Data) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int em_ = 0;
    /**
     * <code>.Enum em = 1;</code>
     * @return The enum numeric value on the wire for em.
     */
    @Override public int getEmValue() {
      return em_;
    }
    /**
     * <code>.Enum em = 1;</code>
     * @param value The enum numeric value on the wire for em to set.
     * @return This builder for chaining.
     */
    public Builder setEmValue(int value) {

      em_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Enum em = 1;</code>
     * @return The em.
     */
    @Override
    public Enum getEm() {
      @SuppressWarnings("deprecation")
      Enum result = Enum.valueOf(em_);
      return result == null ? Enum.UNRECOGNIZED : result;
    }
    /**
     * <code>.Enum em = 1;</code>
     * @param value The em to set.
     * @return This builder for chaining.
     */
    public Builder setEm(Enum value) {
      if (value == null) {
        throw new NullPointerException();
      }

      em_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Enum em = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEm() {

      em_ = 0;
      onChanged();
      return this;
    }

    private Object str_ = "";
    /**
     * <code>string str = 2;</code>
     * @return The str.
     */
    public String getStr() {
      Object ref = str_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        str_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string str = 2;</code>
     * @return The bytes for str.
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      Object ref = str_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string str = 2;</code>
     * @param value The str to set.
     * @return This builder for chaining.
     */
    public Builder setStr(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      str_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string str = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStr() {

      str_ = getDefaultInstance().getStr();
      onChanged();
      return this;
    }
    /**
     * <code>string str = 2;</code>
     * @param value The bytes for str to set.
     * @return This builder for chaining.
     */
    public Builder setStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      str_ = value;
      onChanged();
      return this;
    }

    private long num_ ;
    /**
     * <code>int64 num = 3;</code>
     * @return The num.
     */
    @Override
    public long getNum() {
      return num_;
    }
    /**
     * <code>int64 num = 3;</code>
     * @param value The num to set.
     * @return This builder for chaining.
     */
    public Builder setNum(long value) {

      num_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 num = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNum() {

      num_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTextIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        text_ = new com.google.protobuf.LazyStringArrayList(text_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string text = 4;</code>
     * @return A list containing the text.
     */
    public com.google.protobuf.ProtocolStringList
        getTextList() {
      return text_.getUnmodifiableView();
    }
    /**
     * <code>repeated string text = 4;</code>
     * @return The count of text.
     */
    public int getTextCount() {
      return text_.size();
    }
    /**
     * <code>repeated string text = 4;</code>
     * @param index The index of the element to return.
     * @return The text at the given index.
     */
    public String getText(int index) {
      return text_.get(index);
    }
    /**
     * <code>repeated string text = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the text at the given index.
     */
    public com.google.protobuf.ByteString
        getTextBytes(int index) {
      return text_.getByteString(index);
    }
    /**
     * <code>repeated string text = 4;</code>
     * @param index The index to set the value at.
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
      text_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string text = 4;</code>
     * @param value The text to add.
     * @return This builder for chaining.
     */
    public Builder addText(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
      text_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string text = 4;</code>
     * @param values The text to add.
     * @return This builder for chaining.
     */
    public Builder addAllText(
        Iterable<String> values) {
      ensureTextIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, text_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string text = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string text = 4;</code>
     * @param value The bytes of the text to add.
     * @return This builder for chaining.
     */
    public Builder addTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTextIsMutable();
      text_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        String, String> entry_;
    private com.google.protobuf.MapField<String, String>
    internalGetEntry() {
      if (entry_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EntryDefaultEntryHolder.defaultEntry);
      }
      return entry_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableEntry() {
      onChanged();;
      if (entry_ == null) {
        entry_ = com.google.protobuf.MapField.newMapField(
            EntryDefaultEntryHolder.defaultEntry);
      }
      if (!entry_.isMutable()) {
        entry_ = entry_.copy();
      }
      return entry_;
    }

    public int getEntryCount() {
      return internalGetEntry().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; entry = 5;</code>
     */

    @Override
    public boolean containsEntry(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetEntry().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEntryMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getEntry() {
      return getEntryMap();
    }
    /**
     * <code>map&lt;string, string&gt; entry = 5;</code>
     */
    @Override

    public java.util.Map<String, String> getEntryMap() {
      return internalGetEntry().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; entry = 5;</code>
     */
    @Override

    public String getEntryOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetEntry().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; entry = 5;</code>
     */
    @Override

    public String getEntryOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetEntry().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearEntry() {
      internalGetMutableEntry().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; entry = 5;</code>
     */

    public Builder removeEntry(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableEntry().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableEntry() {
      return internalGetMutableEntry().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; entry = 5;</code>
     */
    public Builder putEntry(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableEntry().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; entry = 5;</code>
     */

    public Builder putAllEntry(
        java.util.Map<String, String> values) {
      internalGetMutableEntry().getMutableMap()
          .putAll(values);
      return this;
    }

    private int uint32_ ;
    /**
     * <code>uint32 uint32 = 6;</code>
     * @return The uint32.
     */
    @Override
    public int getUint32() {
      return uint32_;
    }
    /**
     * <code>uint32 uint32 = 6;</code>
     * @param value The uint32 to set.
     * @return This builder for chaining.
     */
    public Builder setUint32(int value) {

      uint32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 uint32 = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUint32() {

      uint32_ = 0;
      onChanged();
      return this;
    }

    private long uint64_ ;
    /**
     * <code>uint64 uint64 = 7;</code>
     * @return The uint64.
     */
    @Override
    public long getUint64() {
      return uint64_;
    }
    /**
     * <code>uint64 uint64 = 7;</code>
     * @param value The uint64 to set.
     * @return This builder for chaining.
     */
    public Builder setUint64(long value) {

      uint64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 uint64 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUint64() {

      uint64_ = 0L;
      onChanged();
      return this;
    }

    private int fixed32_ ;
    /**
     * <code>fixed32 fixed32 = 8;</code>
     * @return The fixed32.
     */
    @Override
    public int getFixed32() {
      return fixed32_;
    }
    /**
     * <code>fixed32 fixed32 = 8;</code>
     * @param value The fixed32 to set.
     * @return This builder for chaining.
     */
    public Builder setFixed32(int value) {

      fixed32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>fixed32 fixed32 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed32() {

      fixed32_ = 0;
      onChanged();
      return this;
    }

    private long fixed64_ ;
    /**
     * <code>fixed64 fixed64 = 9;</code>
     * @return The fixed64.
     */
    @Override
    public long getFixed64() {
      return fixed64_;
    }
    /**
     * <code>fixed64 fixed64 = 9;</code>
     * @param value The fixed64 to set.
     * @return This builder for chaining.
     */
    public Builder setFixed64(long value) {

      fixed64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>fixed64 fixed64 = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed64() {

      fixed64_ = 0L;
      onChanged();
      return this;
    }

    private int sfixed32_ ;
    /**
     * <code>sfixed32 sfixed32 = 10;</code>
     * @return The sfixed32.
     */
    @Override
    public int getSfixed32() {
      return sfixed32_;
    }
    /**
     * <code>sfixed32 sfixed32 = 10;</code>
     * @param value The sfixed32 to set.
     * @return This builder for chaining.
     */
    public Builder setSfixed32(int value) {

      sfixed32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sfixed32 sfixed32 = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearSfixed32() {

      sfixed32_ = 0;
      onChanged();
      return this;
    }

    private long sfixed64_ ;
    /**
     * <code>sfixed64 sfixed64 = 11;</code>
     * @return The sfixed64.
     */
    @Override
    public long getSfixed64() {
      return sfixed64_;
    }
    /**
     * <code>sfixed64 sfixed64 = 11;</code>
     * @param value The sfixed64 to set.
     * @return This builder for chaining.
     */
    public Builder setSfixed64(long value) {

      sfixed64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sfixed64 sfixed64 = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSfixed64() {

      sfixed64_ = 0L;
      onChanged();
      return this;
    }

    private int sint32_ ;
    /**
     * <code>sint32 sint32 = 12;</code>
     * @return The sint32.
     */
    @Override
    public int getSint32() {
      return sint32_;
    }
    /**
     * <code>sint32 sint32 = 12;</code>
     * @param value The sint32 to set.
     * @return This builder for chaining.
     */
    public Builder setSint32(int value) {

      sint32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 sint32 = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSint32() {

      sint32_ = 0;
      onChanged();
      return this;
    }

    private long sint64_ ;
    /**
     * <code>sint64 sint64 = 13;</code>
     * @return The sint64.
     */
    @Override
    public long getSint64() {
      return sint64_;
    }
    /**
     * <code>sint64 sint64 = 13;</code>
     * @param value The sint64 to set.
     * @return This builder for chaining.
     */
    public Builder setSint64(long value) {

      sint64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint64 sint64 = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearSint64() {

      sint64_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes = 14;</code>
     * @return The bytes.
     */
    @Override
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }
    /**
     * <code>bytes bytes = 14;</code>
     * @param value The bytes to set.
     * @return This builder for chaining.
     */
    public Builder setBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      bytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes bytes = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearBytes() {

      bytes_ = getDefaultInstance().getBytes();
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Data)
  }

  // @@protoc_insertion_point(class_scope:Data)
  private static final Data DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Data();
  }

  public static Data getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Data>
      PARSER = new com.google.protobuf.AbstractParser<Data>() {
    @Override
    public Data parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Data(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Data> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Data> getParserForType() {
    return PARSER;
  }

  @Override
  public Data getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

