// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package test.protobuf;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_EntryEntry_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Data_EntryEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"=\n\007Request\022\014\n\004code\030\001 \001(\005" +
      "\022\017\n\007message\030\002 \001(\014\022\023\n\004data\030\003 \001(\0132\005.Data\"<" +
      "\n\010Response\022\014\n\004code\030\001 \001(\t\022\r\n\005state\030\002 \001(\003\022" +
      "\023\n\004data\030\003 \001(\0132\005.Data\"\220\001\n\004Data\022\021\n\002em\030\001 \001(" +
      "\0162\005.Enum\022\013\n\003str\030\002 \001(\t\022\013\n\003num\030\003 \001(\003\022\014\n\004te" +
      "xt\030\004 \003(\t\022\037\n\005entry\030\005 \003(\0132\020.Data.EntryEntr" +
      "y\032,\n\nEntryEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001*\026\n\004Enum\022\006\n\002E1\020\000\022\006\n\002E2\020\001B\016\n\ntest." +
      "protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Code", "State", "Data", });
    internal_static_Data_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Data_descriptor,
        new java.lang.String[] { "Em", "Str", "Num", "Text", "Entry", });
    internal_static_Data_EntryEntry_descriptor =
      internal_static_Data_descriptor.getNestedTypes().get(0);
    internal_static_Data_EntryEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Data_EntryEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
