// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package test.protobuf;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>bytes message = 2;</code>
   * @return The message.
   */
  com.google.protobuf.ByteString getMessage();

  /**
   * <code>.Data data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.Data data = 3;</code>
   * @return The data.
   */
  Data getData();
  /**
   * <code>.Data data = 3;</code>
   */
  DataOrBuilder getDataOrBuilder();
}
