// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package test.protobuf;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>int64 state = 2;</code>
   * @return The state.
   */
  long getState();

  /**
   * <code>.Data data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.Data data = 3;</code>
   * @return The data.
   */
  test.protobuf.Data getData();
  /**
   * <code>.Data data = 3;</code>
   */
  test.protobuf.DataOrBuilder getDataOrBuilder();
}
