package space.sunqian.fs.sql;

import space.sunqian.annotation.Nonnull;
import space.sunqian.annotation.Nullable;

import java.lang.reflect.Type;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

final class SqlBack {

    static @Nonnull PreparedStatement createPreparedStatement(
        @Nonnull PreparedSql preparedSql, @Nonnull Connection connection
    ) throws SQLException {
        PreparedStatement statement =
            connection.prepareStatement(preparedSql.preparedSql(), Statement.RETURN_GENERATED_KEYS);
        List<Object> parameters = preparedSql.parameters();
        for (int i = 0; i < parameters.size(); i++) {
            statement.setObject(i + 1, parameters.get(i));
        }
        return statement;
    }

    static @Nonnull PreparedStatement createPreparedStatement(
        @Nonnull PreparedBatchSql preparedBatchSql, @Nonnull Connection connection
    ) throws SQLException {
        PreparedStatement statement =
            connection.prepareStatement(preparedBatchSql.preparedSql(), Statement.RETURN_GENERATED_KEYS);
        statement.clearBatch();
        List<List<Object>> batchParameters = preparedBatchSql.batchParameters();
        for (List<Object> batchParameter : batchParameters) {
            for (int i = 0; i < batchParameter.size(); i++) {
                statement.setObject(i + 1, batchParameter.get(i));
            }
            statement.addBatch();
        }
        return statement;
    }

    static <T> @Nonnull SqlQuery<T> newQuery(
        @Nonnull Statement statement,
        @Nonnull Type type
    ) {
        return new SqlQueryImpl<>(statement, type);
    }

    static @Nonnull SqlUpdate newUpdate(@Nonnull Statement statement) {
        return new SqlUpdateImpl(statement);
    }

    static @Nonnull SqlInsert newInsert(
        @Nonnull Statement statement
    ) {
        return new SqlInsertImpl(statement);
    }

    static @Nonnull SqlBatch newBatchResult(
        @Nonnull Statement statement
    ) {
        return new SqlBatchImpl(statement);
    }

    private static final class SqlQueryImpl<T> implements SqlQuery<T> {

        private final @Nonnull Statement statement;
        private final @Nonnull Type type;

        private SqlQueryImpl(
            @Nonnull Statement statement,
            @Nonnull Type type
        ) {
            this.statement = statement;
            this.type = type;
        }

        @Override
        public @Nonnull Type type() {
            return type;
        }

        @Override
        public @Nonnull Statement statement() {
            return statement;
        }
    }

    private static final class SqlUpdateImpl implements SqlUpdate {

        private final @Nonnull Statement statement;

        private SqlUpdateImpl(@Nonnull Statement statement) {
            this.statement = statement;
        }

        @Override
        public @Nonnull Statement statement() {
            return statement;
        }
    }

    private static final class SqlInsertImpl implements SqlInsert {

        private final @Nonnull Statement statement;
        private volatile @Nullable List<@Nonnull Object> autoGeneratedKeys;

        private SqlInsertImpl(@Nonnull Statement statement) {
            this.statement = statement;
        }

        @Override
        public @Nonnull Statement statement() {
            return statement;
        }

        @Override
        public @Nonnull List<@Nonnull Object> autoGeneratedKeys() throws SqlRuntimeException {
            List<@Nonnull Object> keys = autoGeneratedKeys;
            if (keys == null) {
                keys = SqlInsert.super.autoGeneratedKeys();
                autoGeneratedKeys = keys;
            }
            return keys;
        }
    }

    private static final class SqlBatchImpl implements SqlBatch {

        private final @Nonnull Statement statement;

        private SqlBatchImpl(@Nonnull Statement statement) {
            this.statement = statement;
        }

        @Override
        public @Nonnull Statement statement() {
            return statement;
        }
    }

    private SqlBack() {
    }
}